# Generated by Django 3.0.8 on 2021-10-28 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('cpf', models.IntegerField(unique=True)),
                ('rg', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Nenhum', 'Não Informar')], max_length=9)),
                ('data_nascimento', models.DateField(auto_now_add=True)),
                ('cnh', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3)),
                ('salario', models.FloatField()),
                ('carga_horaria', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('horas', models.IntegerField()),
                ('prazo', models.DateField()),
                ('horas_realizadas', models.IntegerField()),
                ('ultimo_calculo_de_horas', models.IntegerField()),
                ('funcionario', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Funcionarios')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('funcionarios', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Funcionarios')),
                ('projeto', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Projeto')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
