# Generated by Django 3.0.8 on 2021-10-31 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='carga_horaria',
            field=models.CharField(max_length=2),
        ),
    ]
