# Generated by Django 3.2.8 on 2021-10-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='departamento',
            field=models.ManyToManyField(related_name='projeto', to='empresa.Departamento'),
        ),
    ]
