# Generated by Django 3.0.8 on 2021-10-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='funcionario',
        ),
        migrations.AddField(
            model_name='projeto',
            name='funcionarios',
            field=models.ManyToManyField(related_name='projeto', to='empresa.Funcionarios'),
        ),
    ]
