# Generated by Django 3.0.8 on 2021-10-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20211030_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='carga_horaria',
            field=models.IntegerField(default=40),
        ),
    ]
