# Generated by Django 3.0.8 on 2021-10-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20211028_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='funcionarios',
            field=models.ManyToManyField(to='empresa.Funcionarios'),
        ),
    ]
