# Generated by Django 3.0.8 on 2021-10-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20211023_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionarios',
            old_name='carga_horária',
            new_name='carga_horaria',
        ),
    ]
