# Generated by Django 3.0.8 on 2021-10-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20211028_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionarios',
            options={'ordering': ['nome']},
        ),
    ]
