# Generated by Django 3.0.8 on 2021-10-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20211024_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='carga_horaria',
            field=models.TimeField(),
        ),
    ]
