# Generated by Django 3.0.8 on 2021-10-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_auto_20211028_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='funcionariosProjeto',
        ),
        migrations.AddField(
            model_name='projeto',
            name='funcionarios',
            field=models.ManyToManyField(blank=True, related_name='projeto', to='empresa.Funcionarios'),
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='projeto',
        ),
        migrations.AddField(
            model_name='departamento',
            name='projeto',
            field=models.ManyToManyField(blank=True, related_name='projeto', to='empresa.Projeto'),
        ),
    ]
