# Generated by Django 3.0.8 on 2021-10-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_auto_20211024_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='funcionarios',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={},
        ),
        migrations.RemoveField(
            model_name='funcionarios',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='funcionarios',
            name='projetos',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='departamento',
        ),
        migrations.AlterField(
            model_name='projeto',
            name='ultimo_calculo_de_horas',
            field=models.IntegerField(),
        ),
    ]
