# Generated by Django 3.0.8 on 2021-10-28 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_auto_20211028_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='funcionarios',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['id']},
        ),
    ]
