# Generated by Django 3.0.8 on 2021-10-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_auto_20211024_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='projeto',
            field=models.ManyToManyField(to='empresa.Projeto'),
        ),
    ]
