# Generated by Django 3.0.8 on 2021-10-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_funcionarios_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='projeto',
            field=models.ManyToManyField(related_name='Funcionarios', to='empresa.Projeto'),
        ),
    ]
