# Generated by Django 3.0.8 on 2021-10-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_auto_20211028_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='supervisor',
            field=models.ManyToManyField(blank=True, related_name='supervisor', to='empresa.Funcionarios'),
        ),
    ]
