# Generated by Django 3.2.8 on 2021-10-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_auto_20211024_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionarios',
            name='projeto',
        ),
    ]
