# Generated by Django 3.0.8 on 2021-10-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0009_projeto_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
