# Generated by Django 3.2.8 on 2021-10-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0010_remove_funcionarios_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='funcionarios',
            field=models.ManyToManyField(to='empresa.Funcionarios'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='projeto',
            field=models.ManyToManyField(to='empresa.Projeto'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='funcionarios',
            field=models.ManyToManyField(to='empresa.Funcionarios'),
        ),
    ]
